### ISSUE TITLE
Release 1.0.0 checklist

### ISSUE THREAD

**Issue by kristerkari** [kristerkari/stylelint-scss#14]
- [x] Complete 1.0.0 milestone
- [x] Check that all rules work and are correctly implemented
- [x] Add CHANGELOG 
- [x] Add project README
- [x] Add list of rules (rules.md, https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md)
- [x] Create plugin/configuration that exposes rules (index.js that imports rules)
- [x] Wait for https://github.com/stylelint/stylelint/issues/1174 to be solved/implemented
- [x] Add missing configuration to build/release `stylelint-scss` to `npm` (no need, everything was already there)
- [x] Rename `extend-require-placeholder` rule to `at-extend-no-missing-placeholder` and fix its readme/projects readme
- [x] Rename `selector-no-redundant-parent` rule to `selector-no-redundant-nesting-selector` and fix its readme/projects readme

**Comment by dryoma** [comment]
I there anything here that could use some help? If so, please point on the items you'd like to assign to me, will be glad to contribute. I have several rule ideas I'd like to propose, but seems it would be better to get the release version up and running and all the way polished.

**Comment by kristerkari** [comment]
> I there anything here that could use some help?

Yes, that would be great! You could create a proper README file that briefly describes the project or you could add missing configuration that allows rules to be used as a stylelint plugin. Just let me know what you want to work on.

**Comment by kristerkari** [comment]
We still need to decide if we want to prefix the rules or not. There is ongoing discussion about it here:
https://github.com/kristerkari/stylelint-scss/issues/12#issuecomment-215483315

**Comment by dryoma** [comment]
I'll be glad to take writing a README (though it would probably be the last thing to be done), and plugin interface. 

At the moment exposing the rules seems unconvenient - multiple plugin, one for each rule, are required. If the stylelint team likes [the idea of "one plugin = multiple rules"](https://github.com/stylelint/stylelint/issues/1174), it will become much simpler.

**Comment by kristerkari** [comment]
Thanks @dryoma! Your help is really appreciated. I really want to get the first version out of the door as fast as possible.

**Comment by kristerkari** [comment]
I added a couple of items to the checklist based on what stylelint has in their repo.

**Comment by evilebottnawi** [comment]
@kristerkari @dryoma You are well done! if you need help, I'm willing to help.

**Comment by kristerkari** [comment]
@evilebottnawi Thanks, there's always something that needs to be done. Right now v1.0 is almost done.

**Comment by jeddy3** [comment]
Quick message (as I'm on my phone and aboard) to say the first release is looking great! I'll be able to look  more closely at things next week, but in the meantime two things stoodout that I thought were worth mentioning now, in case your plan to release soon.

I think extend-require-placeholder should be called at-extend-no-missing-placeholder - Disallow at-extends with missing placeholders. As the convention is that only -no- rules accept true as their primary option.

And selector-no-redundant-parent  should be called selector-no-redundant-nesting - Disallow redundant nesting selectors.

There will likely be core rules in the future that use this name to target the nesting selector (https://tabatkins.github.io/specs/css-nesting/).

What do you think?

Good luck with the release! It's looking excellent :)

**Comment by kristerkari** [comment]
Thanks for the feedback! Naming rules is for me the hardest part when creating new rules. 

- `at-extend-no-missing-placeholder` the word "missing" sounds a bit weird for this rule, but if that is the naming convention, then I guess we'll have to use that. I don't know how I missed the `at-` prefix with that rule, but it definitely needs to be added 🔨 .
-  `selector-no-redundant-nesting` I don't really agree with this one, because the rule is not really checking for nesting. It tries to prevent the use of *parent selector* as part of your nested selector when it's not needed (e.g. a single `& { ... }` or something like  `& > a { ... }`).

**Comment by dryoma** [comment]
Than how about `selector-no-redundant-nesting-selector`? Since "nesting selector" is the name proposed for `&` in the document linked above. Anyway, I think adding a `-selector` part at the end is quite crucial, since the rule not exactly prohibits parents - it is about the `&`.

`at-extend-no-missing-placeholder` - double negation seems a bit odd to me too, but yeah, since that is the convention then there is little choice here.

**Comment by kristerkari** [comment]
> Then how about selector-no-redundant-nesting-selector? Since "nesting selector" is the name proposed for & in the document linked above. Anyway, I think adding a -selector part at the end is quite crucial, since the rule not exactly prohibits parents - it is about the &.

Yeah, `-nesting-selector` sounds much better looking at the draft.

**Comment by jeddy3** [comment]
selector-no-redundant-nesting-selector - that works. I was going to suggest that originally, but then omitted the selector at the end for brevity. I can more see how that makes the rule's purpose ambiguous though.

It's a good rule btw! As in the spec the nesting selector is always required, even for "direct nesting", and so it makes sense that this rule belongs here as the nesting selector is optional in scss (or when using postcss-nested).

**Comment by dryoma** [comment]
`at-extend-no-missing-placeholder`, `selector-no-redundant-nesting` — named these accordingly.
